NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.Buyer.market.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.Buyer.market.com-cert.pem
    OrganizationalUnitIdentifier: peer
